import { Component } from '@angular/core';
import { ProductCard } from '../product-card/product-card';
import { FormsModule } from '@angular/forms';
@Component({
  selector: 'app-product-list',
  imports: [ProductCard,FormsModule],
  templateUrl: './product-list.html',
  styleUrl: './product-list.css',
})
export class ProductList {
  filterKeyword : string = "" ;
  products = [
    {
      id: 1,
      title: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
      price: 109.95,
      description: 'Your perfect pack for everyday use and walks in the forest...',
      category: "men's clothing",
      image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png',
      rating: { rate: 3.9, count: 120 },
      tags: ['backpack', 'laptop', 'outdoor'],
      isFeatured: true,
      inStock: true,
    },
    {
      id: 2,
      title: 'Mens Casual Premium Slim Fit T-Shirts',
      price: 22.3,
      description: 'Slim-fitting style, contrast raglan long sleeve...',
      category: "men's clothing",
      image: 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png',
      rating: { rate: 4.1, count: 259 },
      tags: ['t-shirt', 'casual', 'slim'],
      isFeatured: false,
      inStock: true,
    },
    {
      id: 3,
      title: 'Mens Cotton Jacket',
      price: 55.99,
      description: 'Great outerwear jackets for Spring/Autumn/Winter...',
      category: "men's clothing",
      image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png',
      rating: { rate: 4.7, count: 500 },
      tags: ['jacket', 'cotton', 'warm'],
      isFeatured: true,
      inStock: true,
    },
    {
      id: 4,
      title: 'Mens Casual Slim Fit',
      price: 15.99,
      description: 'The color could be slightly different...',
      category: "men's clothing",
      image: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_t.png',
      rating: { rate: 2.1, count: 430 },
      tags: ['slim', 'shirt', 'casual'],
      isFeatured: false,
      inStock: true,
    },
    {
      id: 5,
      title: "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
      price: 695,
      description: 'From our Legends Collection, the Naga was inspired...',
      category: 'jewelery',
      image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png',
      rating: { rate: 4.6, count: 400 },
      tags: ['bracelet', 'gold', 'silver'],
      isFeatured: true,
      inStock: true,
    },
    {
      id: 6,
      title: 'Solid Gold Petite Micropave',
      price: 168,
      description: 'Satisfaction Guaranteed. Return or exchange...',
      category: 'jewelery',
      image: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_t.png',
      rating: { rate: 3.9, count: 70 },
      tags: ['ring', 'gold', 'micropave'],
      isFeatured: false,
      inStock: true,
    },
    {
      id: 7,
      title: 'White Gold Plated Princess',
      price: 9.99,
      description: 'Classic Created Wedding Engagement Solitaire...',
      category: 'jewelery',
      image: 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_t.png',
      rating: { rate: 3, count: 400 },
      tags: ['ring', 'wedding', 'princess'],
      isFeatured: false,
      inStock: true,
    },
    {
      id: 8,
      title: 'Pierced Owl Rose Gold Plated Stainless Steel Double',
      price: 10.99,
      description: 'Rose Gold Plated Double Flared Tunnel Plug Earrings...',
      category: 'jewelery',
      image: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_t.png',
      rating: { rate: 1.9, count: 100 },
      tags: ['earrings', 'rose gold', 'stainless'],
      isFeatured: false,
      inStock: true,
    },
    {
      id: 9,
      title: 'WD 2TB Elements Portable External Hard Drive - USB 3.0',
      price: 64,
      description: 'USB 3.0 and USB 2.0 Compatibility Fast data transfers...',
      category: 'electronics',
      image: 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_t.png',
      rating: { rate: 3.3, count: 203 },
      tags: ['storage', '2TB', 'usb'],
      isFeatured: true,
      inStock: true,
    },
    {
      id: 10,
      title: 'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s',
      price: 109,
      description: 'Easy upgrade for faster boot up, shutdown...',
      category: 'electronics',
      image: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_t.png',
      rating: { rate: 2.9, count: 470 },
      tags: ['ssd', '1TB', 'internal'],
      isFeatured: false,
      inStock: true,
    },
    {
      id: 11,
      title: 'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5',
      price: 109,
      description: '3D NAND flash are applied to deliver high transfer speeds...',
      category: 'electronics',
      image: 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_t.png',
      rating: { rate: 4.8, count: 319 },
      tags: ['ssd', '256GB', 'performance'],
      isFeatured: true,
      inStock: true,
    },
    {
      id: 12,
      title: 'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive',
      price: 114,
      description: 'Expand your PS4 gaming experience, Play anywhere...',
      category: 'electronics',
      image: 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_t.png',
      rating: { rate: 4.8, count: 400 },
      tags: ['storage', '4TB', 'gaming'],
      isFeatured: true,
      inStock: true,
    },
    {
      id: 13,
      title: 'Acer SB220Q bi 21.5 inches Full HD IPS Ultra-Thin',
      price: 599,
      description: '21.5 inches Full HD widescreen IPS display...',
      category: 'electronics',
      image: 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_t.png',
      rating: { rate: 2.9, count: 250 },
      tags: ['monitor', 'acer', 'ips'],
      isFeatured: false,
      inStock: true,
    },
    {
      id: 14,
      title: 'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor',
      price: 999.99,
      description: '49 INCH SUPER ULTRAWIDE curved gaming monitor...',
      category: 'electronics',
      image: 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_t.png',
      rating: { rate: 2.2, count: 140 },
      tags: ['monitor', 'samsung', 'gaming'],
      isFeatured: false,
      inStock: true,
    },
    {
      id: 15,
      title: "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
      price: 56.99,
      description: 'Note:The Jackets is US standard size...',
      category: "women's clothing",
      image: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_t.png',
      rating: { rate: 2.6, count: 235 },
      tags: ['jacket', 'snowboard', 'winter'],
      isFeatured: true,
      inStock: true,
    },
    {
      id: 16,
      title: "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
      price: 29.95,
      description: 'Faux leather material for style and comfort...',
      category: "women's clothing",
      image: 'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_t.png',
      rating: { rate: 2.9, count: 340 },
      tags: ['jacket', 'leather', 'biker'],
      isFeatured: false,
      inStock: true,
    },
    {
      id: 17,
      title: 'Rain Jacket Women Windbreaker Striped Climbing Raincoats',
      price: 39.99,
      description: 'Lightweight perfet for trip or casual wear...',
      category: "women's clothing",
      image: 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2t.png',
      rating: { rate: 3.8, count: 679 },
      tags: ['raincoat', 'windbreaker', 'climbing'],
      isFeatured: true,
      inStock: true,
    },
    {
      id: 18,
      title: "MBJ Women's Solid Short Sleeve Boat Neck V",
      price: 9.85,
      description: 'Lightweight fabric with great stretch for comfort...',
      category: "women's clothing",
      image: 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_t.png',
      rating: { rate: 4.7, count: 130 },
      tags: ['t-shirt', 'v-neck', 'casual'],
      isFeatured: true,
      inStock: true,
    },
    {
      id: 19,
      title: "Opna Women's Short Sleeve Moisture",
      price: 7.95,
      description: 'Lightweight, roomy and highly breathable...',
      category: "women's clothing",
      image: 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_t.png',
      rating: { rate: 4.5, count: 146 },
      tags: ['t-shirt', 'sport', 'moisture-wicking'],
      isFeatured: false,
      inStock: true,
    },
    {
      id: 20,
      title: 'DANVOUY Womens T Shirt Casual Cotton Short',
      price: 12.99,
      description: '95%Cotton,5%Spandex, Features: Casual, Short Sleeve...',
      category: "women's clothing",
      image: 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_t.png',
      rating: { rate: 3.6, count: 145 },
      tags: ['t-shirt', 'cotton', 'casual'],
      isFeatured: false,
      inStock: true,
    },
  ];
}
